
export const translations = {
  en: {
    app_title: 'Fitness Fuel Calculator',
    form_title: 'Calculate Your Daily Needs',
    form_subtitle: 'Use this calculator to find out your daily calorie needs for maintaining, losing, or gaining weight.',
    age: 'Age',
    age_placeholder: 'Years',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    weight: 'Weight',
    weight_placeholder: 'kg',
    height: 'Height',
    height_placeholder: 'cm',
    activity: 'Activity Level',
    sedentary: 'Sedentary (little or no exercise)',
    light: 'Lightly active (light exercise/sports 1-3 days/week)',
    moderate: 'Moderately active (moderate exercise/sports 3-5 days/week)',
    very: 'Very active (hard exercise/sports 6-7 days a week)',
    extra: 'Extra active (very hard exercise & physical job)',
    calculate: 'Calculate',
    results_title: 'Your Results',
    results_subtitle: 'Based on your input, here are your estimated daily calorie needs:',
    maintain: 'Maintain weight',
    mild_loss: 'Mild weight loss',
    mild_loss_desc: '0.25 kg/week',
    normal_loss: 'Weight loss',
    normal_loss_desc: '0.5 kg/week',
    extreme_loss: 'Extreme weight loss',
    extreme_loss_desc: '1 kg/week',
    calories_day: 'Calories/day',
    disclaimer_title: 'Disclaimer',
    disclaimer_text: 'The results are an estimate and should not be taken as medical advice. Your daily calorie needs may vary. Consult with a nutritionist or doctor for personalized advice.',
    error_incomplete: 'Please fill in all fields.',
    error_invalid: 'Please enter valid numbers for age, weight, and height.',
    initial_results_message: 'Your results will be displayed here once you fill out the form and click "Calculate".',
  },
  ar: {
    app_title: 'حاسبة وقود اللياقة',
    form_title: 'احسب احتياجاتك اليومية',
    form_subtitle: 'استخدم هذه الحاسبة لمعرفة احتياجاتك اليومية من السعرات الحرارية للحفاظ على وزنك، أو فقدانه، أو زيادته.',
    age: 'العمر',
    age_placeholder: 'سنوات',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    weight: 'الوزن',
    weight_placeholder: 'كجم',
    height: 'الطول',
    height_placeholder: 'سم',
    activity: 'مستوى النشاط',
    sedentary: 'خامل (قليل أو بدون تمرين)',
    light: 'نشاط خفيف (تمرين خفيف/رياضة 1-3 أيام/أسبوع)',
    moderate: 'نشاط معتدل (تمرين معتدل/رياضة 3-5 أيام/أسبوع)',
    very: 'نشيط جدًا (تمرين شاق/رياضة 6-7 أيام في الأسبوع)',
    extra: 'نشاط فائق (تمرين شاق جداً وعمل بدني)',
    calculate: 'احسب',
    results_title: 'نتائجك',
    results_subtitle: 'بناءً على بياناتك، هذه هي احتياجاتك اليومية التقديرية من السعرات الحرارية:',
    maintain: 'الحفاظ على الوزن',
    mild_loss: 'فقدان طفيف للوزن',
    mild_loss_desc: '0.25 كجم/أسبوع',
    normal_loss: 'فقدان الوزن',
    normal_loss_desc: '0.5 كجم/أسبوع',
    extreme_loss: 'فقدان كبير للوزن',
    extreme_loss_desc: '1 كجم/أسبوع',
    calories_day: 'سعرة حرارية/يوم',
    disclaimer_title: 'إخلاء مسؤولية',
    disclaimer_text: 'النتائج هي تقديرية ولا يجب اعتبارها نصيحة طبية. قد تختلف احتياجاتك اليومية من السعرات الحرارية. استشر أخصائي تغذية أو طبيبًا للحصول على نصائح شخصية.',
    error_incomplete: 'يرجى ملء جميع الحقول.',
    error_invalid: 'يرجى إدخال أرقام صالحة للعمر والوزن والطول.',
    initial_results_message: 'ستُعرض نتائجك هنا بمجرد ملء النموذج والضغط على "احسب".',
  },
};
